### ISSUE TITLE
Exception thrown for Annotations

### ISSUE THREAD

**Issue by ckindermann** [hsolbrig/funowl#25]
Trying to load the latest version of [UBERON](https://bioportal.bioontology.org/ontologies/UBERON) using the function [`to_python`](https://github.com/hsolbrig/funowl/blob/edee9e00d066f2a3eb4671cc7af98b386c98a26d/funowl/converters/functional_converter.py#L325) throws the error `TypeError: __init__() got multiple values for argument 'annotations'`. (I converted UBERON to OWL Functional-Style Syntax with Protégé.)

**Comment by hsolbrig** [comment]
Note that, as of now, you still have to convert Uberon from XML to Functional syntax to load it.   We'll be looking at incorporating [Robot](https://github.com/ontodev/robot) into the workflow to cover this bit
