### ISSUE TITLE
UserWarning: Code: f is not defined in namespace XSD

### ISSUE THREAD

**Issue by cmungall** [hsolbrig/funowl#40]
sometimes generation will make this:

```
/Users/cthoyt/.virtualenvs/obo/lib/python3.10/site-packages/funowl/literals.py:180: UserWarning: Code: f is not defined in namespace XSD
  l = g.value(XSD.f, RDF.type)
```

(I will prepare a full test case later)

**Comment by hsolbrig** [comment]
I'm curious why this doesn't ALWAYS generate a warning, as "f" is not a valid XML Schema value, no?

**Comment by hsolbrig** [comment]
Never mind -- I have it in my unit tests -- I need to change that 'f' to something else.  Will do

**Comment by hsolbrig** [comment]
Fixed.  There may be other edge cases of this sort that leak out -- I should probably put together a "kitchen sink" literal -- maybe just embed a significant chunk of an ontology in a literal to make sure that the parser doesn't burp.   I debated using a parser like ANTLR or PyParsing, but the language was just on the edge of making it worthwhile...
